---
latitude: '64.5609'
longitude: '21.9010'
map_zoom: 12
name: Hotel B59, Borgarnes
email: <a href="mailto:hotelb59iceland@gmail.com">hotelb59iceland@gmail.com</a>
phone_number: <a href="tel:0011111111">001-111-1111</a>
default_currency: ISK
address:
  street1: Hotel B59
  street2: ''
  state: Borgarbyggd
  city: Borgarnes
  country: Iceland
  zip_code: '310'
_hotel_id: TIHB59
_portal_id: hotelb59
logo: <img id="1513696923238" class=" " src="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/LOGO.jpg"
  data-image-large="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/large_LOGO.jpg"
  data-image-medium="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/medium_LOGO.jpg"
  data-image-small="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/small_LOGO.jpg"
  data-image-xsmall="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/xsmall_LOGO.jpg"
  data-image-thumb="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/thumb_LOGO.jpg"
  />
footer_logo: "<strong>HOTEL B59</strong>"
footer_last_column: <img id="1515135925794" class=" " src="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-15-061831/2016.12.20-Hotel-B59-Iceland-Bar-002.jpg"
  width="370" height="278" data-image-large="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-15-061831/large_2016.12.20_Hotel_B59_Iceland_Bar_002.jpg"
  data-image-medium="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-15-061831/medium_2016.12.20_Hotel_B59_Iceland_Bar_002.jpg"
  data-image-small="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-15-061831/small_2016.12.20_Hotel_B59_Iceland_Bar_002.jpg"
  data-image-xsmall="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-15-061831/xsmall_2016.12.20_Hotel_B59_Iceland_Bar_002.jpg"
  data-image-thumb="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-15-061831/thumb_2016.12.20_Hotel_B59_Iceland_Bar_002.jpg"
  />
