---
latitude: '64.5609'
longitude: '21.9010'
map_zoom: 12
name: Hotel B59, Borgarnes
email: hotelb59iceland@gmail.com
phone_number: 001-111-1111
address:
  street1: Hotel B59
  street2: ''
  state: Borgarbyggd
  city: Borgarnes
  country: Iceland
  zip_code: '310'
_hotel_id: TIHB59
_portal_id: required-but-empty
logo: "<h2><strong>HOTEL B59</strong></h2>"
footer_logo: Hotel B59
