---
latitude: 15.49731
longitude: 73.76723
map_zoom: 12
name: Taj Fort Aguada Resort & Spa, Goa
email: vishal@traveltripper.com
phone_number: 001-111-1111
address:
  street1: Borgarnes
  street2: ''
  state: ''
  city: Candolim
  country: 
  zip_code: '403519'
_hotel_id: TAJ545
_portal_id: required-but-empty
logo: HOTEL B59
