---
latitude: '64.5609'
longitude: '21.9010'
map_zoom: 12
name: Hotel B59, Borgarnes
email: hotelb59iceland@gmail.com
phone_number: 001-111-1111
address:
  street1: Hotel B59
  street2: ''
  state: Borgarbyggd
  city: Borgarnes
  country: Iceland
  zip_code: '310'
_hotel_id: TIHB59
_portal_id: hotelb59
logo: <img id="1513696923238" class=" " src="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/LOGO.jpg"
  data-image-large="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/large_LOGO.jpg"
  data-image-medium="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/medium_LOGO.jpg"
  data-image-small="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/small_LOGO.jpg"
  data-image-xsmall="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/xsmall_LOGO.jpg"
  data-image-thumb="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/thumb_LOGO.jpg"
  />
footer_logo: <img id="1513696984138" class=" " src="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/LOGO.jpg"
  width="270" height="69" data-image-large="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/large_LOGO.jpg"
  data-image-medium="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/medium_LOGO.jpg"
  data-image-small="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/small_LOGO.jpg"
  data-image-xsmall="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/xsmall_LOGO.jpg"
  data-image-thumb="//cdn.traveltripper.io/site-assets/32_820_8437/media/2017-12-19-102200/thumb_LOGO.jpg"
  />
